### ISSUE TITLE
table formspecs

### ISSUE THREAD

**Issue by bobombolo** [rubenwardy/minetest_modding_book#19]
this page at the minetest dev wiki:
http://dev.minetest.net/Lua_Table_Formspec
implies that a formspec can be built with a table, but there is no examples of how to do this
even the examples on the page show
<pre>
{"invsize", w=8, h=9}
{"list", inventorylocation="context", listname="main", x=0, y=0, w=8, h=4}
{"list", inventorylocation="current_player", listname="main", x=0, y=5, w=8, h=4}
</pre>
but there are no commas after each line, and no indication what the overall wrapper is and minetest.show_formspec() won't accept a table as input to the third argument...

yet a table with named indexes is superior to the cryptic string formspecs...

**Comment by rubenwardy** [comment]
There's no reference of this in lua_api.txt D:
