### ISSUE TITLE
Use fixed navbar

### ISSUE THREAD

**Issue by SmallJoker** [rubenwardy/minetest_modding_book#21]
I think it would be better to have a fixed navbar, that follows you when scrolling down.
This way it's possible to switch easily without having to scroll up/page up.

```css
#navbar {
	position: absolute;
```
->
```css
#navbar {
	position: fixed;
```
https://github.com/rubenwardy/minetest_modding_book/blob/gh-pages/static/style.scss#L64

**Comment by rubenwardy** [comment]
You'd also have to make sure that it isn't fixed if the screen height isn't big enough. Will do as soon as I have access to a computer.

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/minetest_modding_book/commit/04c23632090944fc22ea85be1de9685a9bb98ceb
