### ISSUE TITLE
the doc say viscosity is about speed of the spread

### ISSUE THREAD

**Issue by asl97** [rubenwardy/minetest_modding_book#22]
i would have make a pull request but i can't think of a good name for the commit.

file: https://github.com/rubenwardy/minetest_modding_book/blob/gh-pages/chapters/node_drawtypes.md#liquid

patch: https://github.com/asl97/minetest_modding_book/commit/0ed276906859e334f2c1b0eb90c2d35e583e3c47.patch

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/minetest_modding_book/commit/b69b6f47324bc78cc38ed5b778d7951393c09579
