### ISSUE TITLE
Hash anchors on headers are not very visible

### ISSUE THREAD

**Issue by Ferk** [rubenwardy/minetest_modding_book#24]
It would be cool if for every header in the manual, we could click and obtain a hash link that we can send people for referencing that particular section of the manual.

Like for example I can use the link:
http://rubenwardy.com/minetest_modding_book/chapters/nodes_items_crafting.html#shapeless
And be directed to the section about adding shapeless items automatically. But I don't have a way to obtain that link, I wouldn't have even known it was possible if I hadn't some some checking. 

This would be particularly useful when the document is very long, like the Lua API reference. 
I know that reference has an index with links at the beginning, but it's not easy to have to scroll all the way up to get the link and have to remember the exact name of the section. Also, it's a pity that bullet points (list items) are not indexable in there, I'm not sure if this is easily doable.. but it would be a fine thing to have.

**Comment by rubenwardy** [comment]
If you have Javascript enabled, then the hash links appear. Unfortunately I can't do this any other way unless I do preprocessing, which would make it very annoying and more complicated to contribute and deploy.

![hash_linkl](https://cloud.githubusercontent.com/assets/2122943/11319036/247bf672-9061-11e5-9d14-8e4ba73d198b.png)

**Comment by rubenwardy** [comment]
Added LibreJS support to the code: https://github.com/rubenwardy/minetest_modding_book/commit/f18854d8c6c72ce14619612e33bf66f056af1663

**Comment by rubenwardy** [comment]
I'd also like to add line numbers to the Lua api, to make it easier.

**Comment by Ferk** [comment]
Owww.. I'm sorry, I didn't notice the faded out hash symbol on the right side. I was on a wide screen so I didn't see those gray "#" on the right.

Then it's already implemented.

Maybe you could make it so clicking the header has also the same effect? Or maybe somehow highlight or "unhide" the hash symbol when you hover the header/line, in a similar way as it happens in github.

But maybe that's eye candy. It's already ok for me having realized about the hashes.

Imho, it's fine to use something else than line numbers, so that when the api reference gets updated and line numbers change the old links may still point to the right places if the headers or the name of the functions was used.

**Comment by rubenwardy** [comment]
The problem is that headers don't appear enough. I'll see if I can make an algorithm to add more headers at good places.

**Comment by rubenwardy** [comment]
> I'll see if I can make an algorithm to add more headers at good places.

Done: 478809867649fa04e7aa040dda3c3176c62b2b22

**Comment by Ferk** [comment]
Awesome!
