### ISSUE TITLE
Mesh Nodes

### ISSUE THREAD

**Issue by 4Evergreen4** [rubenwardy/minetest_modding_book#26]
- mesh node drawtype
- creating models for mesh node

**Comment by rubenwardy** [comment]
Covered by #2, however it's arguable that nodeboxes and mesh nodes deserve their own chapter.

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/minetest_modding_book/commit/f8151907f8d41fdb0a60717814cd1f6b21e0b486
