### ISSUE TITLE
explain gimp transparency

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/minetest_modding_book#29]
> One thing I miss is an explanation of how you make the background transparent using the Gimp. I use a different program to edit the pixels in .gif, then open it with the Gimp and save it as .png, but although I managed to adjust the paintbrush and eraser sizes following your instructions I haven't been able to figure out how to do the transparency bit.

**Comment by hy8wGWme** [comment]
where do you want to insert this information in?

To make the picture transparent i just press shift-o toggether for color picker click on the background color then layer-transparency-color to alpha-choose the right color-press ok and the picture is transparent

**Comment by rubenwardy** [comment]
It would be in making textures
