### ISSUE TITLE
Itemstacks chapter is not given green highlight when selected

### ISSUE THREAD

**Issue by whitephoenix0** [rubenwardy/minetest_modding_book#33]
When chapters are selected they are given a green highlight in the sidebar, however the itemstacks chapter does not. 

Pictures:
Example of selected: http://i.imgur.com/lpT7BSr.png
Itemstack's problem: http://i.imgur.com/cbIiqgM.png

Tried fixing it myself but I don't know much about jekyll.

**Comment by rubenwardy** [comment]
The title needs to be changed to a plural here https://github.com/rubenwardy/minetest_modding_book/blob/gh-pages/chapters/itemstacks.md
