### ISSUE TITLE
[Feature Request] Page navigation buttons at the end of pages

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/minetest_modding_book#62]
Currently, readers would've to scroll all the way back up in order to go to the next page. I suggest adding "Next ->" and "<- Previous" buttons at the end of every page.

**Comment by rubenwardy** [comment]
This is painful to do and would require lots of hackery

**Comment by ClobberXD** [comment]
Then I'll try my hand at this sometime soon... :)

**Comment by rubenwardy** [comment]
I think this would need 2 for loops over the navigation list, one forwards and one in reverse. It would then set a flag when the current page is found then render the next one. So very gross though.

Worth seeing if there's a find then doing indices, something like this would be ideal:

```jekyll
{% assign next = site.data.nav_en[site.data.nav_en.find(title=page.title).key + 1] %}
```

ie: it finds the current page then adds 1 or minuses 1. I don't think this exists, however. Plus it won't work with `hr` entries (which may not be needed soon)

**Comment by ClobberXD** [comment]
Hmm... true. I guess it'll have to wait :/

**Comment by rubenwardy** [comment]
I'm going to be removing the hr elements in favour of sections anyway, so it may become easier

**Comment by rubenwardy** [comment]
![](https://i.rubenwardy.com/Xs36v.png)
