### ISSUE TITLE
Writing mistake

### ISSUE THREAD

**Issue by Max1Truc** [rubenwardy/minetest_modding_book#65]
There are two mistakes on the third line of the second code given under this section https://rubenwardy.com/minetest_modding_book/en/chapters/sfinv.html#conditionally-showing-to-players

You wrote "mientest" instead of "minetest" and "grantee" instead of "granter"

**Comment by pauloue** [comment]
I think the "grantee" is correct. The grantee is the player who is receiving or losing privs so we need to update their formspec.

**Comment by rubenwardy** [comment]
grantee is correct. It could be changed to `name` instead, to be more clear

**Comment by Max1Truc** [comment]
Sorry, you're right about grantee, but what about "mientest" ?

**Comment by rubenwardy** [comment]
Already fixed
