### ISSUE TITLE
In sfinv chapter there is no examples for having item slots

### ISSUE THREAD

**Issue by Extex101** [rubenwardy/minetest_modding_book#99]
Please add some examples for a sfinv extra inv type page

**Comment by rubenwardy** [comment]
Why should there be? It's a general formspec thing, not at all related to sfinv

**Comment by Extex101** [comment]
OK could you at least have some examples for item slots in formspecs
Because whenever I try all I get is this:
![Screenshot_2019-05-27-11-11-09-1](https://user-images.githubusercontent.com/33675971/58434408-55760080-8070-11e9-9664-7e1703d280a4.png)

And here's my code. 
```
sfinv.register_page("rings:ring_page", {
	title = "Rings",
	get = function(self, player, context)
	    local formspec = "list[current_player;rings;1.75,0.5;2,3;]"
		  return sfinv.make_formspec(player, context, formspec, true)
	end
})
```
I can't seem to find anything anywhere saying how to do this

**Comment by pauloue** [comment]
Probably the current player doesn't have a 'rings' list.

**Comment by Extex101** [comment]
How do I fix that?

**Comment by pauloue** [comment]
I think you can do
```lua
minetest.register_on_joinplayer(function(player)                                 
    local inv = player:get_inventory()                                           
    inv:set_size("rings", SIZE)                                              
end)
```

**Comment by Extex101** [comment]
Oh XD I've been trying different solutions for days I found this 30 line on_joinplayer from the bags mod.
And that was all that was needed XD
